version: '3.2'

services:
  nginx:
    image: nginx-app
    container_name: nginx-server
    build: ./nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elk

networks:
  elk:
    driver: bridge
  